spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fridayboot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: fridayboot
    password: fridayboot
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    # password:
    timeout: 10000
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0