spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fridayboot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: fridayboot
    password: fridayboot
    driver-class-name: com.mysql.cj.jdbc.Driver